name: Build GDPS for Linux
on: [push] # Собирать при каждом пуше в репозиторий

jobs:
  build:
    runs-on: ubuntu-latest # Используем Linux сервер GitHub
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Prepare GDPS Package
        run: |
          mkdir -p release/MyGDPS-Linux
          
          # 1. Скачиваем твой ZIP из релизов
          wget https://github.com/AlbeePython/axiom-launcher/releases/download/release_1.0/Axiom.Dash._.ADPS.zip -O game.zip
          
          # 2. Распаковываем его в папку для линукса
          unzip game.zip -d release/MyGDPS-Linux/
          
          # 3. Создаем скрипт запуска
          echo '#!/bin/bash' > release/MyGDPS-Linux/start.sh
          # ВАЖНО: Проверь, как называется .exe внутри зипки. 
          # Если он называется "Axiom Dash.exe", то пиши: wine "Axiom Dash | ADPS.exe"
          echo 'wine "Axiom Dash.exe"' >> release/MyGDPS-Linux/start.sh
          
          # 4. Даем права на запуск скрипту
          chmod +x release/MyGDPS-Linux/start.sh

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: MyGDPS-Linux-Version
          path: release/MyGDPS-Linux/
