name: Build GDPS for Linux
on: [push] # Собирать при каждом пуше в репозиторий

jobs:
  build:
    runs-on: ubuntu-latest # Используем Linux сервер GitHub
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Prepare GDPS Package
        run: |
          mkdir -p release/MyGDPS-Linux
          
          # 1. Скачиваем с флагом -L (чтобы GitHub отдал файл, а не ошибку)
          curl -L "https://github.com/AlbeePython/axiom-launcher/releases/download/release_1.0/" -o Axiom.Dash._.ADPS.zip
          
          # 2. Распаковываем
          unzip Axiom.Dash._.ADPS.zip -d release/MyGDPS-Linux/
          
          # 3. Исправляем имя файла с чертой | (из-за которого была прошлая ошибка)
          cd release/MyGDPS-Linux/
          # Эта команда найдет файл с чертой и заменит её на нижнее подчеркивание
          find . -name "*|*" -exec bash -c 'mv "$1" "${1//|/_}"' -- {} \;
          
          # 4. Создаем скрипт запуска
          echo '#!/bin/bash' > start.sh
          # Ищем любой .exe файл и прописываем его в запуск (автоматически)
          EXE_NAME=$(ls *.exe | head -n 1)
          echo "wine \"$EXE_NAME\"" > start.sh
          chmod +x start.sh

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: MyGDPS-Linux-Version
          path: release/MyGDPS-Linux/
